name       : kcachegrind
version    : 21.12.3
release    : 9
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kcachegrind-21.12.3.tar.xz : ddcf3722211d47c90616528607ebc4573835faa52a57e2e9d6763968b9975ab3
license    : GPL-2.0-only
component  : desktop.kde
summary    : Visualization of Performance Profiling Data
description: |
    kcachegrind is a KDE GUI to visualize profiling data. It's mainly used as visualization frontend for data measured by Cachegrind/Callgrind tools from the Valgrind package, but there are converters for other measurement tools available.
builddeps  :
    - karchive-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - kwidgetsaddons-devel
rundeps    :
    - valgrind
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
