name       : kcachegrind
version    : 21.04.3
release    : 1
source     :
    - https://download.kde.org/stable/release-service/21.04.3/src/kcachegrind-21.04.3.tar.xz : 25d01173e31b8715bd1b22546ef9c39cf4f555d9860a106d34588bae55793926
license    : GPL-2.0-only
component  : desktop.kde
summary    : Visualization of Performance Profiling Data
description: |
    kcachegrind is a KDE GUI to visualize profiling data. It's mainly used as visualization frontend for data measured by Cachegrind/Callgrind tools from the Valgrind package, but there are converters for other measurement tools available.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - karchive-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - valgrind
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
