name       : kcachegrind
version    : 21.08.2
release    : 5
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/kcachegrind-21.08.2.tar.xz : 898492e020308e05ea3edc8738f83ee0d79480d86b07713469e2f3150c50d888
license    : GPL-2.0-only
component  : desktop.kde
summary    : Visualization of Performance Profiling Data
description: |
    kcachegrind is a KDE GUI to visualize profiling data. It's mainly used as visualization frontend for data measured by Cachegrind/Callgrind tools from the Valgrind package, but there are converters for other measurement tools available.
builddeps  :
    - karchive-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - kwidgetsaddons-devel
rundeps    :
    - valgrind
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
