name       : kcachegrind
version    : 21.08.1
release    : 4
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kcachegrind-21.08.1.tar.xz : fb8bbbba0178f33c8a4bdace2fdfe747036822b5fa9013b5905a1de5198def27
license    : GPL-2.0-only
component  : desktop.kde
summary    : Visualization of Performance Profiling Data
description: |
    kcachegrind is a KDE GUI to visualize profiling data. It's mainly used as visualization frontend for data measured by Cachegrind/Callgrind tools from the Valgrind package, but there are converters for other measurement tools available.
builddeps  :
    - karchive-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - kwidgetsaddons-devel
rundeps    :
    - valgrind
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
