name       : kcachegrind
version    : 22.12.1
release    : 15
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/kcachegrind-22.12.1.tar.xz : da8e6fcae433a49671174994a5eb24a69a42bcaa4e169ffbf5bd50d883b02f06
license    : GPL-2.0-only
component  : desktop.kde
summary    : Visualization of Performance Profiling Data
description: |
    kcachegrind is a KDE GUI to visualize profiling data. It's mainly used as visualization frontend for data measured by Cachegrind/Callgrind tools from the Valgrind package, but there are converters for other measurement tools available.
builddeps  :
    - karchive-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - kwidgetsaddons-devel
rundeps    :
    - valgrind
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
