name       : kcachegrind
version    : 23.04.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kcachegrind-23.04.2.tar.xz : 9bb17cc9e85e396e8591d06e04974d6f106b1d8de00596af77555afc93915902
license    : GPL-2.0-only
component  : desktop.kde
summary    : Visualization of Performance Profiling Data
description: |
    kcachegrind is a KDE GUI to visualize profiling data. It's mainly used as visualization frontend for data measured by Cachegrind/Callgrind tools from the Valgrind package, but there are converters for other measurement tools available.
builddeps  :
    - karchive-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - kwidgetsaddons-devel
rundeps    :
    - valgrind
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
